using System.Collections.Generic;
using UnityEditor;
using UnityEngine;

namespace AzipaWorks.BlendshapeEditor
{
    internal enum BseLanguage
    {
        Japanese,
        English,
        Chinese,
        Korean,
    }

    /// <summary>
    /// 表示言語の切り替え。コード中の日本語をそのままキーにして、ほかの言語の訳を引く。
    /// 訳が無い文字列は日本語のまま表示する。
    /// </summary>
    internal static class BseLocalization
    {
        private const string PrefKey = "AzipaTools.BlendshapeEditor.Language";

        public static readonly string[] LanguageLabels = { "日本語", "English", "简体中文", "한국어" };

        /// <summary>選んだ言語（未設定のときは Unity を動かしている OS の言語に合わせる）</summary>
        public static BseLanguage Language
        {
            get => (BseLanguage)EditorPrefs.GetInt(PrefKey, (int)SystemDefault());
            set => EditorPrefs.SetInt(PrefKey, (int)value);
        }

        private static BseLanguage SystemDefault()
        {
            switch (Application.systemLanguage)
            {
                case SystemLanguage.Japanese: return BseLanguage.Japanese;
                case SystemLanguage.Chinese:
                case SystemLanguage.ChineseSimplified:
                case SystemLanguage.ChineseTraditional: return BseLanguage.Chinese;
                case SystemLanguage.Korean: return BseLanguage.Korean;
                default: return BseLanguage.English;
            }
        }

        public static string T(string japanese)
        {
            var lang = Language;
            if (lang == BseLanguage.Japanese || japanese == null) return japanese;
            return Table.TryGetValue(japanese, out var tr) ? tr[(int)lang - 1] : japanese;
        }

        public static string T(string japanese, params object[] args) => string.Format(T(japanese), args);

        // 日本語 → { English, 简体中文, 한국어 }
        private static readonly Dictionary<string, string[]> Table = new Dictionary<string, string[]>
        {
            // ---------------------------------------------------------------- タブ・共通
            { "作成", new[] { "Create", "创建", "만들기" } },
            { "管理", new[] { "Manage", "管理", "관리" } },
            { "作成シェイプ一覧", new[] { "Created Shapes", "已创建形态键", "만든 셰이프 목록" } },
            { "並び順", new[] { "Order", "排列顺序", "순서" } },
            { "アバター管理", new[] { "Avatars", "Avatar 管理", "아바타 관리" } },
            { "設定", new[] { "Settings", "设置", "설정" } },
            { "キャンセル", new[] { "Cancel", "取消", "취소" } },
            { "削除", new[] { "Delete", "删除", "삭제" } },
            { "削除する", new[] { "Delete", "删除", "삭제" } },
            { "それでも削除する", new[] { "Delete Anyway", "仍然删除", "그래도 삭제" } },
            { "編集", new[] { "Edit", "编辑", "편집" } },
            { "適用", new[] { "Apply", "应用", "적용" } },
            { "選ぶ", new[] { "Select", "选择", "선택" } },
            { "選択を外す", new[] { "Deselect", "取消选择", "선택 해제" } },
            { "まだありません。", new[] { "None yet.", "暂无。", "아직 없습니다." } },
            { "（なし）", new[] { "(None)", "（无）", "(없음)" } },
            { " ほか {0} 個", new[] { " and {0} more", " 等 {0} 个", " 외 {0}개" } },
            { " ほか {0} 体", new[] { " and {0} more", " 等 {0} 个", " 외 {0}개" } },
            { "\nほか {0} 体", new[] { "\nand {0} more", "\n等 {0} 个", "\n외 {0}개" } },
            { "\nほか {0} 件", new[] { "\nand {0} more", "\n等 {0} 项", "\n외 {0}건" } },
            { "{0} 個", new[] { "{0}", "{0} 个", "{0}개" } },

            // ---------------------------------------------------------------- 対象メッシュ・空の状態
            { "対象メッシュ", new[] { "Target Mesh", "目标网格", "대상 메시" } },
            { "選択中", new[] { "Selected", "使用选中", "선택 항목" } },
            { "使用中のファイル", new[] { "File in Use", "使用中的文件", "사용 중인 파일" } },
            { "（作ったシェイプ {0} 個）", new[] { "({0} created shapes)", "（已创建 {0} 个形态键）", "(만든 셰이프 {0}개)" } },
            { "（まだシェイプを作っていません）", new[] { "(No shapes created yet)", "（尚未创建形态键）", "(아직 만든 셰이프가 없습니다)" } },
            { "対象メッシュを指定してください", new[] { "Assign a target mesh", "请指定目标网格", "대상 메시를 지정하세요" } },
            { "シェイプキーを持つ顔の SkinnedMeshRenderer を、上の欄にドラッグ＆ドロップするか、\n",
                new[] { "Drag and drop the face SkinnedMeshRenderer that has shape keys into the field above,\n",
                    "请将带有形态键的脸部 SkinnedMeshRenderer 拖放到上方栏中，\n",
                    "셰이프 키가 있는 얼굴의 SkinnedMeshRenderer를 위 칸에 드래그 앤 드롭하거나,\n" } },
            { "Hierarchy で選んで「選択中」を押してください。",
                new[] { "or select it in the Hierarchy and press \"Selected\".", "或在 Hierarchy 中选中后点击“使用选中”。", "Hierarchy에서 선택한 뒤 \"선택 항목\"을 누르세요." } },
            { "シェイプを作る前の顔のデータ（FBX など）が見つかりません。削除・移動していないか確認してください。\n",
                new[] { "The original face data (FBX, etc.) used before creating shapes cannot be found. Check that it has not been deleted or moved.\n",
                    "找不到创建形态键前的脸部数据（FBX 等）。请确认其是否已被删除或移动。\n",
                    "셰이프를 만들기 전의 얼굴 데이터(FBX 등)를 찾을 수 없습니다. 삭제하거나 이동하지 않았는지 확인하세요.\n" } },
            { "このデータが無いとシェイプを正しく作り直せないため、編集できません。",
                new[] { "Shapes cannot be rebuilt correctly without this data, so editing is disabled.", "没有此数据就无法正确重建形态键，因此无法编辑。", "이 데이터가 없으면 셰이프를 올바르게 다시 만들 수 없으므로 편집할 수 없습니다." } },
            { "このメッシュにはシェイプキーがありません。", new[] { "This mesh has no shape keys.", "此网格没有形态键。", "이 메시에는 셰이프 키가 없습니다." } },
            { "シーン上のオブジェクトを指定してください（Project 内のプレハブは編集できません）。",
                new[] { "Assign an object in the scene (prefabs in the Project cannot be edited).", "请指定场景中的对象（无法编辑 Project 中的 Prefab）。", "씬 위의 오브젝트를 지정하세요(Project 안의 프리팹은 편집할 수 없습니다)." } },

            // ---------------------------------------------------------------- ライセンス
            { "Blendshape Editor のライセンスが見つかりません", new[] { "Blendshape Editor license not found", "未找到 Blendshape Editor 许可证", "Blendshape Editor 라이선스를 찾을 수 없습니다" } },
            { "このコンピュータには Blendshape Editor の使用が許諾されていません。\n",
                new[] { "This computer is not licensed to use Blendshape Editor.\n", "此电脑未获得 Blendshape Editor 的使用许可。\n", "이 컴퓨터에는 Blendshape Editor 사용이 허가되어 있지 않습니다.\n" } },
            { "Booth で Blendshape Editor を購入し、ダウンロードした ZIP に入っている「{0}」を",
                new[] { "Purchase Blendshape Editor on Booth and import \"{0}\" from the downloaded ZIP ",
                    "请在 Booth 购买 Blendshape Editor，并将下载的 ZIP 中的“{0}”",
                    "Booth에서 Blendshape Editor를 구입하고, 다운로드한 ZIP에 들어 있는 \"{0}\"을(를) " } },
            { "Unity にインポートしてください（この作業は 1 台のコンピュータにつき 1 回だけ必要です）。\n\n",
                new[] { "into Unity (this only needs to be done once per computer).\n\n",
                    "导入 Unity（每台电脑只需操作一次）。\n\n",
                    "Unity에 임포트하세요(컴퓨터 1대당 한 번만 하면 됩니다).\n\n" } },
            { "購入済みなのにこの画面が表示される場合は、Booth から最新の ZIP をダウンロードして、",
                new[] { "If you see this screen even though you have purchased it, download the latest ZIP from Booth ",
                    "如果已购买仍显示此画面，请从 Booth 下载最新的 ZIP，",
                    "구입했는데도 이 화면이 표시되면 Booth에서 최신 ZIP을 다운로드하고 " } },
            { "ライセンスインストーラーをインポートし直してください。\n\n",
                new[] { "and import the license installer again.\n\n", "并重新导入许可证安装程序。\n\n", "라이선스 인스톨러를 다시 임포트하세요.\n\n" } },
            { "作成済みのシェイプ（保存ファイル）は、ライセンスが無くてもアバターでそのまま使えます。",
                new[] { "Shapes you have already created (saved files) keep working on your avatars without a license.",
                    "已创建的形态键（保存的文件）即使没有许可证也可以继续在 Avatar 上使用。",
                    "이미 만든 셰이프(저장 파일)는 라이선스가 없어도 아바타에서 그대로 사용할 수 있습니다." } },
            { "Booth で購入する", new[] { "Buy on Booth", "在 Booth 购买", "Booth에서 구입" } },
            { "Booth（準備中）", new[] { "Booth (Coming Soon)", "Booth（准备中）", "Booth(준비 중)" } },
            { "ライセンスを再確認", new[] { "Check License Again", "重新检查许可证", "라이선스 다시 확인" } },
            { "ライセンスをインストールした直後に押してください", new[] { "Press this right after installing the license", "安装许可证后请立即点击", "라이선스를 설치한 직후에 누르세요" } },
            { "このコンピュータには Blendshape Editor のライセンスがインストールされていません。",
                new[] { "No Blendshape Editor license is installed on this computer.", "此电脑未安装 Blendshape Editor 许可证。", "이 컴퓨터에는 Blendshape Editor 라이선스가 설치되어 있지 않습니다." } },
            { "Blendshape Editor ライセンス削除", new[] { "Remove Blendshape Editor License", "删除 Blendshape Editor 许可证", "Blendshape Editor 라이선스 삭제" } },
            { "このコンピュータから Blendshape Editor のライセンスを削除しますか？\n\n",
                new[] { "Remove the Blendshape Editor license from this computer?\n\n", "要从此电脑删除 Blendshape Editor 许可证吗？\n\n", "이 컴퓨터에서 Blendshape Editor 라이선스를 삭제하시겠습니까?\n\n" } },
            { "もう一度使うには、ライセンスインストーラー（{0}）をインポートし直す必要があります。\n",
                new[] { "To use it again, you will need to import the license installer ({0}) again.\n", "如需再次使用，需要重新导入许可证安装程序（{0}）。\n", "다시 사용하려면 라이선스 인스톨러({0})를 다시 임포트해야 합니다.\n" } },
            { "作成したシェイプ（保存ファイル）は削除されず、アバターでそのまま使えます。",
                new[] { "Created shapes (saved files) are not deleted and keep working on your avatars.", "已创建的形态键（保存的文件）不会被删除，可继续在 Avatar 上使用。", "만든 셰이프(저장 파일)는 삭제되지 않으며 아바타에서 그대로 사용할 수 있습니다." } },
            { "ライセンスを削除しました。", new[] { "The license has been removed.", "已删除许可证。", "라이선스를 삭제했습니다." } },

            // ---------------------------------------------------------------- 作成タブ
            { "シェイプの種類", new[] { "Shape Type", "形态键类型", "셰이프 종류" } },
            { "シェイプ作成・上書き編集", new[] { "Create / Overwrite Shape", "创建・覆盖编辑形态键", "셰이프 만들기·덮어쓰기 편집" } },
            { "元にするシェイプを組み合わせて、新しいシェイプを作ったり既存のシェイプを上書きしたりします",
                new[] { "Combine source shapes to create a new shape or overwrite an existing one", "组合源形态键，创建新的形态键或覆盖现有形态键", "기반 셰이프를 조합해 새 셰이프를 만들거나 기존 셰이프를 덮어씁니다" } },
            { "UI用シェイプ作成", new[] { "UI Separator Shape", "创建 UI 用形态键", "UI용 셰이프 만들기" } },
            { "シェイプキー一覧を見やすく区切るための空のシェイプです（例: ---- VRCHAT ----）。顔は変形しません",
                new[] { "An empty shape used to divide the shape key list for readability (e.g. ---- VRCHAT ----). It does not deform the face",
                    "用于分隔形态键列表、便于查看的空形态键（例：---- VRCHAT ----）。不会改变脸部形状",
                    "셰이프 키 목록을 보기 쉽게 구분하기 위한 빈 셰이프입니다(예: ---- VRCHAT ----). 얼굴은 변형되지 않습니다" } },
            { "クリア", new[] { "Clear", "清空", "지우기" } },
            { "入力内容を消して新しく作り始めます", new[] { "Clear the inputs and start over", "清空输入内容并重新开始", "입력 내용을 지우고 새로 시작합니다" } },
            { "UI用シェイプの名前", new[] { "Separator Name", "UI 用形态键名称", "UI용 셰이프 이름" } },
            { "例: ---- 表情 ----", new[] { "e.g. ---- Expressions ----", "例：---- 表情 ----", "예: ---- 표정 ----" } },
            { "整形", new[] { "Format", "格式化", "정리" } },
            { "「---- 名前 ----」の形に整えます", new[] { "Format as \"---- Name ----\"", "整理为“---- 名称 ----”的格式", "\"---- 이름 ----\" 형식으로 정리합니다" } },
            { "区切り", new[] { "Separator", "分隔", "구분" } },
            { "UI用シェイプは顔を変形しない空のシェイプです。シェイプキー一覧を見やすく区切るために使います。",
                new[] { "A separator shape is an empty shape that does not deform the face. Use it to divide the shape key list for readability.",
                    "UI 用形态键是不会改变脸部形状的空形态键，用于分隔形态键列表、便于查看。",
                    "UI용 셰이프는 얼굴을 변형하지 않는 빈 셰이프입니다. 셰이프 키 목록을 보기 쉽게 구분하는 데 사용합니다." } },
            { "作成済みの「{0}」を上書きします。", new[] { "This will overwrite the created shape \"{0}\".", "将覆盖已创建的“{0}”。", "이미 만든 \"{0}\"을(를) 덮어씁니다." } },
            { "既存シェイプを編集する", new[] { "Edit an existing shape", "编辑现有形态键", "기존 셰이프 편집" } },
            { "選んだシェイプと同じ名前で出力し、元にするシェイプにもそのシェイプを設定します。\n",
                new[] { "Outputs with the same name as the selected shape and also adds that shape as a source.\n",
                    "以与所选形态键相同的名称输出，并将该形态键也设为源形态键。\n",
                    "선택한 셰이프와 같은 이름으로 출력하고, 기반 셰이프에도 그 셰이프를 설정합니다.\n" } },
            { "元のシェイプは退避名で残ります", new[] { "The original shape is kept under a backup name", "原形态键将以备份名称保留", "원래 셰이프는 백업 이름으로 남습니다" } },
            { "編集するシェイプ", new[] { "Shape to Edit", "要编辑的形态键", "편집할 셰이프" } },
            { "(シェイプを選択)", new[] { "(Select a shape)", "（选择形态键）", "(셰이프 선택)" } },
            { "出力シェイプ名", new[] { "Output Shape Name", "输出形态键名称", "출력 셰이프 이름" } },
            { "既存の「{0}」と同じ名前・同じ位置に新しいシェイプを入れます。\n",
                new[] { "A new shape will be placed with the same name and position as the existing \"{0}\".\n",
                    "将在与现有“{0}”相同的名称和位置放入新的形态键。\n",
                    "기존 \"{0}\"과(와) 같은 이름, 같은 위치에 새 셰이프를 넣습니다.\n" } },
            { "元のシェイプは「{0}」", new[] { "The original shape is kept as \"{0}\"", "原形态键将作为“{0}”", "원래 셰이프는 \"{0}\"(으)로" } },
            { "として「{0}」の下に残します。", new[] { " under \"{0}\".", "保留在“{0}”下方。", " \"{0}\" 아래에 남깁니다." } },
            { "元にするシェイプ（新シェイプ 100 のときの値）", new[] { "Source Shapes (values when the new shape is 100)", "源形态键（新形态键为 100 时的值）", "기반 셰이프(새 셰이프가 100일 때의 값)" } },
            { "{0} で 0 以外の値が入っているシェイプだけから選ぶ", new[] { "Only choose from shapes with non-zero values on {0}", "仅从 {0} 上值不为 0 的形态键中选择", "{0}에서 0이 아닌 값이 들어 있는 셰이프에서만 선택" } },
            { "シェイプ選択リストを、今のメッシュ上で値が設定されているものに絞り込みます",
                new[] { "Narrow the shape list to shapes that have a value set on the current mesh", "将形态键选择列表限定为当前网格上已设置值的形态键", "셰이프 선택 목록을 현재 메시에서 값이 설정된 것으로 좁힙니다" } },
            { "限界突破", new[] { "Exceed Limits", "突破上限", "한계 돌파" } },
            { "値を ±100 を超えて設定できるようにします。100 を超えた分は同じ方向に直線的に伸びます",
                new[] { "Allow values beyond ±100. Anything over 100 extends linearly in the same direction",
                    "允许设置超过 ±100 的值。超过 100 的部分会沿同一方向线性延伸",
                    "값을 ±100을 넘어 설정할 수 있게 합니다. 100을 넘는 부분은 같은 방향으로 직선적으로 늘어납니다" } },
            { "上限 ±", new[] { "Limit ±", "上限 ±", "상한 ±" } },
            { "±100 を超える値は形が破綻しやすいので、プレビューで確認しながら調整してください。",
                new[] { "Values beyond ±100 can easily break the shape, so adjust while checking the preview.",
                    "超过 ±100 的值容易导致形状崩坏，请一边查看预览一边调整。",
                    "±100을 넘는 값은 형태가 망가지기 쉬우므로 미리보기로 확인하면서 조정하세요." } },
            { "現在 {0:0.#}", new[] { "Now {0:0.#}", "当前 {0:0.#}", "현재 {0:0.#}" } },
            { "{0} 上の現在の値", new[] { "Current value on {0}", "{0} 上的当前值", "{0}의 현재 값" } },
            { "打消", new[] { "Cancel Out", "抵消", "상쇄" } },
            { "値を −現在値 にして、新シェイプ 100 でこのシェイプを 0 と同じ状態にする",
                new[] { "Set the value to minus the current value, so this shape looks like 0 when the new shape is 100",
                    "将值设为“−当前值”，使新形态键为 100 时此形态键与 0 的状态相同",
                    "값을 −현재 값으로 하여, 새 셰이프가 100일 때 이 셰이프를 0과 같은 상태로 만듭니다" } },
            { "＋ シェイプを追加", new[] { "+ Add Shape", "＋ 添加形态键", "+ 셰이프 추가" } },
            { "左右分割", new[] { "Left/Right Split", "左右分割", "좌우 분할" } },
            { "分割", new[] { "Split", "分割", "분할" } },
            { "しない", new[] { "None", "不分割", "안 함" } },
            { "左側のみ", new[] { "Left Side Only", "仅左侧", "왼쪽만" } },
            { "右側のみ", new[] { "Right Side Only", "仅右侧", "오른쪽만" } },
            { "境目のぼかし幅 (m)", new[] { "Boundary Blend Width (m)", "边界过渡宽度 (m)", "경계 블러 폭 (m)" } },
            { "アバター中心（X=0）を境に、この幅でなめらかに左右を分けます",
                new[] { "Splits left and right smoothly over this width around the avatar center (X=0)", "以 Avatar 中心（X=0）为界，在此宽度内平滑地分开左右", "아바타 중심(X=0)을 경계로 이 폭만큼 부드럽게 좌우를 나눕니다" } },
            { "左右はキャラクター本人から見た向きです（アバターが +Z を向いている前提）。",
                new[] { "Left and right are from the character's own point of view (assuming the avatar faces +Z).",
                    "左右为角色本人视角的方向（假设 Avatar 朝向 +Z）。",
                    "좌우는 캐릭터 본인 시점의 방향입니다(아바타가 +Z를 향한다는 전제)." } },
            { "追加する位置", new[] { "Insert Position", "添加位置", "추가할 위치" } },
            { "位置", new[] { "Position", "位置", "위치" } },
            { "完成したシェイプキー一覧の中で、どこに入れるかを選びます", new[] { "Choose where to place it in the final shape key list", "选择放在最终形态键列表中的哪个位置", "완성된 셰이프 키 목록에서 어디에 넣을지 선택합니다" } },
            { "既定の位置（新規は末尾、既存は今の位置）", new[] { "Default (new: at the end, existing: current position)", "默认位置（新建为末尾，现有为当前位置）", "기본 위치(새 셰이프는 끝, 기존은 현재 위치)" } },
            { "先頭", new[] { "Top", "最前", "맨 앞" } },
            { "「{0}」の下", new[] { "Below \"{0}\"", "“{0}”下方", "\"{0}\" 아래" } },
            { "{0} の下", new[] { "Below {0}", "{0} 下方", "{0} 아래" } },
            { "変更しない（今の位置）", new[] { "Keep (current position)", "不变（当前位置）", "변경 안 함(현재 위치)" } },
            { "末尾（退避用の見出しの上）", new[] { "End (above the backup header)", "末尾（备份标题上方）", "끝(백업용 제목 위)" } },
            { "シェイプキーがありません", new[] { "No shape keys", "没有形态键", "셰이프 키가 없습니다" } },
            { "途中に入れると、後ろのシェイプの番号がずれます。編集中のアバターの瞬き・視線は自動で付け直します",
                new[] { "Inserting in the middle shifts the indices of the shapes after it. Blink/eye look settings on the avatar being edited are fixed automatically",
                    "插入到中间会使后面形态键的编号错位。正在编辑的 Avatar 的眨眼・视线会自动重新设置",
                    "중간에 넣으면 뒤쪽 셰이프의 번호가 밀립니다. 편집 중인 아바타의 눈 깜빡임·시선은 자동으로 다시 설정합니다" } },
            { "（他のアバターは「管理 › アバター管理」で付け直せます）。",
                new[] { " (other avatars can be fixed in \"Manage › Avatars\").", "（其他 Avatar 可在“管理 › Avatar 管理”中重新设置）。", "(다른 아바타는 \"관리 › 아바타 관리\"에서 다시 설정할 수 있습니다)." } },
            { "表示 ON", new[] { "Show ON", "显示 ON", "표시 ON" } },
            { "表示 OFF", new[] { "Show OFF", "显示 OFF", "표시 OFF" } },
            { "シーンへのプレビュー表示を切り替えます", new[] { "Toggle the preview in the scene", "切换场景中的预览显示", "씬의 미리보기 표시를 전환합니다" } },
            { "新シェイプの値", new[] { "New Shape Value", "新形态键的值", "새 셰이프 값" } },
            { "「{0}」を更新", new[] { "Update \"{0}\"", "更新“{0}”", "\"{0}\" 업데이트" } },
            { "「{0}」に保存します。作成済みのシェイプは「管理」タブの「作成シェイプ一覧」で確認できます。",
                new[] { "Saves to \"{0}\". Created shapes can be reviewed in \"Created Shapes\" on the \"Manage\" tab.",
                    "保存到“{0}”。已创建的形态键可在“管理”标签的“已创建形态键”中查看。",
                    "\"{0}\"에 저장합니다. 만든 셰이프는 \"관리\" 탭의 \"만든 셰이프 목록\"에서 확인할 수 있습니다." } },
            { "初回は保存先を選びます。シェイプを追加した顔のデータを新しいファイル（.asset）として保存し、対象メッシュに適用します。元の FBX は変更しません。",
                new[] { "The first time, you choose where to save. The face data with the added shapes is saved as a new file (.asset) and applied to the target mesh. The original FBX is not modified.",
                    "首次需选择保存位置。添加了形态键的脸部数据将保存为新文件（.asset）并应用到目标网格。不会修改原 FBX。",
                    "처음에는 저장 위치를 선택합니다. 셰이프를 추가한 얼굴 데이터를 새 파일(.asset)로 저장하고 대상 메시에 적용합니다. 원래 FBX는 변경하지 않습니다." } },

            // ---------------------------------------------------------------- プレビュー
            { "{0}  値 {1:0}", new[] { "{0}  value {1:0}", "{0}  值 {1:0}", "{0}  값 {1:0}" } },
            { "●  プレビュー中　{0}", new[] { "●  Previewing  {0}", "●  预览中　{0}", "●  미리보기 중  {0}" } },
            { "○  プレビュー OFF　実際のメッシュを表示中", new[] { "○  Preview OFF  Showing the actual mesh", "○  预览 OFF　正在显示实际网格", "○  미리보기 OFF  실제 메시 표시 중" } },
            { "○  待機中　出力シェイプ名と元にするシェイプを設定してください",
                new[] { "○  Waiting  Set the output shape name and source shapes", "○  待机中　请设置输出形态键名称和源形态键", "○  대기 중  출력 셰이프 이름과 기반 셰이프를 설정하세요" } },
            { "○  実際のメッシュを表示中", new[] { "○  Showing the actual mesh", "○  正在显示实际网格", "○  실제 메시 표시 중" } },
            { "表示のために顔のデータを一時的に差し替えています。保存・ウィンドウを閉じる・シーン保存・再生で自動的に元に戻ります",
                new[] { "The face data is temporarily replaced for display. It is restored automatically when you save, close the window, save the scene, or enter Play mode",
                    "为了显示，正在临时替换脸部数据。保存、关闭窗口、保存场景或运行时会自动恢复",
                    "표시를 위해 얼굴 데이터를 임시로 교체하고 있습니다. 저장, 창 닫기, 씬 저장, 재생 시 자동으로 원래대로 돌아갑니다" } },
            { "[{0}] プレビューを表示できなかったため、プレビューを OFF にしました。",
                new[] { "[{0}] The preview could not be shown, so it has been turned OFF.", "[{0}] 无法显示预览，已关闭预览。", "[{0}] 미리보기를 표시할 수 없어 미리보기를 OFF로 했습니다." } },
            { "「{0}」は既存のシェイプと同じ名前です。UI用シェイプには別の名前を付けてください。",
                new[] { "\"{0}\" has the same name as an existing shape. Give the separator shape a different name.",
                    "“{0}”与现有形态键同名。请为 UI 用形态键设置其他名称。",
                    "\"{0}\"은(는) 기존 셰이프와 같은 이름입니다. UI용 셰이프에는 다른 이름을 붙이세요." } },
            { "「{0}」は作成済みの「{1}」と名前が重複しています。出力シェイプ名を変えてください。",
                new[] { "\"{0}\" conflicts with the name of the created shape \"{1}\". Change the output shape name.",
                    "“{0}”与已创建的“{1}”名称重复。请更改输出形态键名称。",
                    "\"{0}\"은(는) 이미 만든 \"{1}\"과(와) 이름이 겹칩니다. 출력 셰이프 이름을 바꾸세요." } },

            // ---------------------------------------------------------------- 作成シェイプ一覧
            { "まだ作成したシェイプはありません。「作成」タブで作成してください。",
                new[] { "No shapes have been created yet. Create one on the \"Create\" tab.", "尚未创建形态键。请在“创建”标签中创建。", "아직 만든 셰이프가 없습니다. \"만들기\" 탭에서 만드세요." } },
            { "以前保存したファイル（.asset）がある場合は、対象メッシュのレンダラーにそのファイルを割り当てると読み込めます。",
                new[] { "If you have a previously saved file (.asset), assign it to the target mesh's renderer to load it.",
                    "如果有以前保存的文件（.asset），将其分配给目标网格的渲染器即可读取。",
                    "이전에 저장한 파일(.asset)이 있다면 대상 메시의 렌더러에 그 파일을 할당하면 불러올 수 있습니다." } },
            { "作成したシェイプの一覧です。行をクリックすると詳細を表示します。",
                new[] { "A list of the shapes you have created. Click a row to show its details.", "已创建形态键的列表。点击行可显示详细信息。", "만든 셰이프 목록입니다. 행을 클릭하면 자세한 내용을 표시합니다." } },
            { "すべて展開", new[] { "Expand All", "全部展开", "모두 펼치기" } },
            { "すべてたたむ", new[] { "Collapse All", "全部折叠", "모두 접기" } },
            { "クリックで詳細を閉じる", new[] { "Click to hide details", "点击关闭详细信息", "클릭하여 자세한 내용 닫기" } },
            { "クリックで詳細を表示", new[] { "Click to show details", "点击显示详细信息", "클릭하여 자세한 내용 표시" } },
            { "元にするシェイプが見つからないものがあります。詳細を確認してください",
                new[] { "Some source shapes cannot be found. Check the details", "有找不到的源形态键。请查看详细信息", "찾을 수 없는 기반 셰이프가 있습니다. 자세한 내용을 확인하세요" } },
            { "UI用シェイプ", new[] { "Separator", "UI 用形态键", "UI용 셰이프" } },
            { "既存シェイプの上書き", new[] { "Overwrites Existing", "覆盖现有形态键", "기존 셰이프 덮어쓰기" } },
            { "新規", new[] { "New", "新建", "신규" } },
            { "顔を変形しない、一覧を見やすくするための空のシェイプです",
                new[] { "An empty shape that does not deform the face, used to make the list easier to read", "不改变脸部形状、用于让列表更易查看的空形态键", "얼굴을 변형하지 않고 목록을 보기 쉽게 하기 위한 빈 셰이프입니다" } },
            { "既存のシェイプを置き換えています", new[] { "Replaces an existing shape", "正在替换现有形态键", "기존 셰이프를 대체하고 있습니다" } },
            { "新しい名前で追加しています", new[] { "Added with a new name", "以新名称添加", "새 이름으로 추가하고 있습니다" } },
            { "顔を変形しない UI 用のシェイプです。", new[] { "A separator shape that does not deform the face.", "不改变脸部形状的 UI 用形态键。", "얼굴을 변형하지 않는 UI용 셰이프입니다." } },
            { "元にするシェイプ", new[] { "Source Shapes", "源形态键", "기반 셰이프" } },
            { "・{0}　{1:0.#}", new[] { "• {0}  {1:0.#}", "・{0}　{1:0.#}", "• {0}  {1:0.#}" } },
            { "元のシェイプは {0} に退避しています", new[] { "The original shape is backed up as {0}", "原形态键已备份为 {0}", "원래 셰이프는 {0}(으)로 백업되어 있습니다" } },
            { "アバターの顔のデータに見つからないシェイプがあります: {0}\n",
                new[] { "Some shapes cannot be found in the avatar's face data: {0}\n", "在 Avatar 的脸部数据中找不到以下形态键：{0}\n", "아바타의 얼굴 데이터에서 찾을 수 없는 셰이프가 있습니다: {0}\n" } },
            { "見つからないシェイプは無視して作成されます。", new[] { "Missing shapes are ignored when creating.", "创建时将忽略找不到的形态键。", "찾을 수 없는 셰이프는 무시하고 만듭니다." } },
            { "このシェイプは作成されません（設定は残っています）。「編集」で元にするシェイプを選び直してください。",
                new[] { "This shape will not be created (its settings are kept). Use \"Edit\" to choose the source shapes again.",
                    "此形态键不会被创建（设置仍保留）。请通过“编辑”重新选择源形态键。",
                    "이 셰이프는 만들어지지 않습니다(설정은 남아 있습니다). \"편집\"에서 기반 셰이프를 다시 선택하세요." } },
            { "「{0}」を削除しますか？\n既存を置き換えていた場合は元のシェイプに戻ります。\n",
                new[] { "Delete \"{0}\"?\nIf it replaced an existing shape, the original shape will be restored.\n",
                    "要删除“{0}”吗？\n如果它替换了现有形态键，将恢复为原形态键。\n",
                    "\"{0}\"을(를) 삭제하시겠습니까?\n기존 셰이프를 대체하고 있었다면 원래 셰이프로 돌아갑니다.\n" } },
            { "この操作は Undo で取り消せません（もう一度作成すれば元に戻せます）。",
                new[] { "This cannot be undone with Undo (you can restore it by creating it again).", "此操作无法通过 Undo 撤销（重新创建即可恢复）。", "이 작업은 Undo로 취소할 수 없습니다(다시 만들면 되돌릴 수 있습니다)." } },

            // ---------------------------------------------------------------- 並び順
            { "シェイプキーの並び順を変更します。ドラッグ＆ドロップかボタンで並べ替えて、「並び順を保存」で反映します。",
                new[] { "Change the order of the shape keys. Reorder by drag and drop or with the buttons, then apply with \"Save Order\".",
                    "更改形态键的排列顺序。通过拖放或按钮重新排列，然后点击“保存排列顺序”应用。",
                    "셰이프 키의 순서를 변경합니다. 드래그 앤 드롭이나 버튼으로 정렬한 뒤 \"순서 저장\"으로 반영합니다." } },
            { "Avatar Descriptor の瞬き・視線はシェイプを番号で参照しているため、並び替えると参照がずれます。",
                new[] { "Avatar Descriptor blink/eye look settings refer to shapes by index, so reordering shifts them.",
                    "Avatar Descriptor 的眨眼・视线是按编号引用形态键的，因此重新排列会导致引用错位。",
                    "Avatar Descriptor의 눈 깜빡임·시선은 셰이프를 번호로 참조하므로, 순서를 바꾸면 참조가 어긋납니다." } },
            { "保存時に編集中のアバターは自動で付け直します。同じファイルを使う他のアバターは「アバター管理」で付け直してください。",
                new[] { " The avatar being edited is fixed automatically on save. Fix other avatars using the same file in \"Avatars\".",
                    "保存时会自动重新设置正在编辑的 Avatar。使用同一文件的其他 Avatar 请在“Avatar 管理”中重新设置。",
                    " 저장 시 편집 중인 아바타는 자동으로 다시 설정합니다. 같은 파일을 쓰는 다른 아바타는 \"아바타 관리\"에서 다시 설정하세요." } },
            { "↶ 元に戻す", new[] { "↶ Undo", "↶ 撤销", "↶ 실행 취소" } },
            { "直前の並べ替えを取り消します（Ctrl+Z）", new[] { "Undo the last reorder (Ctrl+Z)", "撤销上一次排列（Ctrl+Z）", "직전의 정렬을 취소합니다(Ctrl+Z)" } },
            { "やり直す ↷", new[] { "Redo ↷", "重做 ↷", "다시 실행 ↷" } },
            { "取り消した並べ替えをやり直します（Ctrl+Y）", new[] { "Redo the undone reorder (Ctrl+Y)", "重做已撤销的排列（Ctrl+Y）", "취소한 정렬을 다시 실행합니다(Ctrl+Y)" } },
            { "変更前と比較", new[] { "Compare with Before", "与修改前比较", "변경 전과 비교" } },
            { "保存済みの並び（左）と編集中の並び（右）を並べて表示します",
                new[] { "Show the saved order (left) and the order being edited (right) side by side", "并排显示已保存的顺序（左）和正在编辑的顺序（右）", "저장된 순서(왼쪽)와 편집 중인 순서(오른쪽)를 나란히 표시합니다" } },
            { "移動したものだけ（{0}）", new[] { "Moved only ({0})", "仅显示已移动（{0}）", "이동한 것만({0})" } },
            { "並べ替えで動かしたシェイプだけを表示します", new[] { "Show only the shapes moved by reordering", "仅显示因排列而移动的形态键", "정렬로 움직인 셰이프만 표시합니다" } },
            { "選択 {0} / 全 {1}", new[] { "Selected {0} / {1}", "已选 {0} / 共 {1}", "선택 {0} / 전체 {1}" } },
            { "先頭へ", new[] { "To Top", "移到最前", "맨 앞으로" } },
            { "上へ", new[] { "Up", "上移", "위로" } },
            { "下へ", new[] { "Down", "下移", "아래로" } },
            { "末尾へ", new[] { "To End", "移到末尾", "맨 끝으로" } },
            { "{0} (並び順: {1})", new[] { "{0} (Order: {1})", "{0}（排列顺序：{1}）", "{0} (순서: {1})" } },
            { "変更前（保存済み）", new[] { "Before (Saved)", "修改前（已保存）", "변경 전(저장됨)" } },
            { "変更後（編集中）", new[] { "After (Editing)", "修改后（编辑中）", "변경 후(편집 중)" } },
            { "退避", new[] { "Backup", "备份", "백업" } },
            { "UI用", new[] { "UI", "UI 用", "UI용" } },
            { "退避の見出し", new[] { "Backup Header", "备份标题", "백업 제목" } },
            { "上書き", new[] { "Overwrite", "覆盖", "덮어쓰기" } },
            { "並べ替えで移動したシェイプです", new[] { "This shape was moved by reordering", "此形态键因排列而移动", "정렬로 이동한 셰이프입니다" } },
            { "退避したシェイプは、退避用の見出しの下にまとめて置かれます",
                new[] { "Backed-up shapes are grouped under the backup header", "备份的形态键会集中放在备份标题下方", "백업한 셰이프는 백업용 제목 아래에 모아 둡니다" } },
            { "ドラッグで移動", new[] { "Drag", "拖动移动", "드래그로 이동" } },
            { "検索・絞り込み中はドラッグできません。ボタンで移動してください。",
                new[] { "Dragging is disabled while searching or filtering. Use the buttons to move.", "搜索或筛选时无法拖动。请使用按钮移动。", "검색·필터 중에는 드래그할 수 없습니다. 버튼으로 이동하세요." } },
            { "左が保存済み、右が編集中の並びです。動かしたシェイプは色付きで、右に移動量（↑↓）、左に移動先の番号を表示します。",
                new[] { "Left is the saved order and right is the order being edited. Moved shapes are colored, with the amount moved (↑↓) on the right and the new index on the left.",
                    "左侧为已保存的顺序，右侧为正在编辑的顺序。移动过的形态键会着色，右侧显示移动量（↑↓），左侧显示移动后的编号。",
                    "왼쪽은 저장된 순서, 오른쪽은 편집 중인 순서입니다. 움직인 셰이프는 색으로 표시하고, 오른쪽에 이동량(↑↓), 왼쪽에 이동한 번호를 표시합니다." } },
            { "未保存の変更があります（移動したシェイプ {0} 個）。", new[] { "There are unsaved changes ({0} shapes moved).", "有未保存的更改（已移动 {0} 个形态键）。", "저장하지 않은 변경 사항이 있습니다(이동한 셰이프 {0}개)." } },
            { "元の並びに戻す", new[] { "Reset to Default Order", "恢复默认顺序", "기본 순서로 되돌리기" } },
            { "ツールの既定の並び（元の顔のデータの順・作成したシェイプ・退避用の見出し）に戻します",
                new[] { "Reset to the tool's default order (original face data order, created shapes, backup header)",
                    "恢复为工具的默认顺序（原脸部数据的顺序、已创建的形态键、备份标题）",
                    "도구의 기본 순서(원래 얼굴 데이터 순서, 만든 셰이프, 백업용 제목)로 되돌립니다" } },
            { "変更を取り消す", new[] { "Discard Changes", "放弃更改", "변경 취소" } },
            { "並び順を保存", new[] { "Save Order", "保存排列顺序", "순서 저장" } },
            { "シェイプキーの並び順を保存します。\n\n", new[] { "Save the shape key order.\n\n", "将保存形态键的排列顺序。\n\n", "셰이프 키 순서를 저장합니다.\n\n" } },
            { "Avatar Descriptor の瞬き・視線はシェイプを番号で参照しているため、並び替えると参照がずれます。\n",
                new[] { "Avatar Descriptor blink/eye look settings refer to shapes by index, so reordering shifts them.\n",
                    "Avatar Descriptor 的眨眼・视线是按编号引用形态键的，因此重新排列会导致引用错位。\n",
                    "Avatar Descriptor의 눈 깜빡임·시선은 셰이프를 번호로 참조하므로, 순서를 바꾸면 참조가 어긋납니다.\n" } },
            { "・編集中のアバター：自動で付け直します\n", new[] { "• Avatar being edited: fixed automatically\n", "・正在编辑的 Avatar：自动重新设置\n", "• 편집 중인 아바타: 자동으로 다시 설정합니다\n" } },
            { "・同じファイルを使う他のアバター：「管理 › アバター管理」で付け直してください\n\n保存しますか？",
                new[] { "• Other avatars using the same file: fix them in \"Manage › Avatars\"\n\nSave?",
                    "・使用同一文件的其他 Avatar：请在“管理 › Avatar 管理”中重新设置\n\n要保存吗？",
                    "• 같은 파일을 쓰는 다른 아바타: \"관리 › 아바타 관리\"에서 다시 설정하세요\n\n저장하시겠습니까?" } },
            { "保存する", new[] { "Save", "保存", "저장" } },

            // ---------------------------------------------------------------- アバター管理
            { "シーンのアバターに、作ったシェイプを反映したり、作る前の状態に戻したりします。",
                new[] { "Apply your created shapes to avatars in the scene, or restore them to their previous state.",
                    "将创建的形态键应用到场景中的 Avatar，或恢复为创建前的状态。",
                    "씬의 아바타에 만든 셰이프를 반영하거나, 만들기 전 상태로 되돌립니다." } },
            { "反映するファイル", new[] { "File to Apply", "要应用的文件", "반영할 파일" } },
            { "作る前のファイル", new[] { "Original File", "创建前的文件", "만들기 전 파일" } },
            { "反映前の記録が無いアバターは、「反映前に戻す」とこのファイルになります",
                new[] { "Avatars with no pre-apply record are restored to this file by \"Restore\"", "没有应用前记录的 Avatar 在“恢复到应用前”后会变为此文件", "반영 전 기록이 없는 아바타는 \"반영 전으로 되돌리기\"를 하면 이 파일이 됩니다" } },
            { "チェックを入れて「反映」または「反映前に戻す」を押してください。",
                new[] { "Check avatars and press \"Apply\" or \"Restore\".", "勾选后点击“应用”或“恢复到应用前”。", "체크한 뒤 \"반영\" 또는 \"반영 전으로 되돌리기\"를 누르세요." } },
            { "反映したアバターは、このあと更新した内容も自動で反映されます。どちらの操作も Undo で取り消せます。",
                new[] { "Applied avatars also receive later updates automatically. Both operations can be undone with Undo.",
                    "已应用的 Avatar 之后更新的内容也会自动应用。两种操作都可以通过 Undo 撤销。",
                    "반영한 아바타는 이후 업데이트한 내용도 자동으로 반영됩니다. 두 작업 모두 Undo로 취소할 수 있습니다." } },
            { "{0} 体（反映済み {1}・未反映 {2}）", new[] { "{0} avatars (applied {1}, not applied {2})", "{0} 个（已应用 {1}・未应用 {2}）", "{0}개(반영됨 {1}·미반영 {2})" } },
            { "未反映をすべて選ぶ", new[] { "Select Not Applied", "全选未应用", "미반영 모두 선택" } },
            { "反映済みをすべて選ぶ", new[] { "Select Applied", "全选已应用", "반영됨 모두 선택" } },
            { "瞬き・視線の設定がずれているアバターが {0} 体あります。",
                new[] { "{0} avatars have shifted blink/eye look settings. ", "有 {0} 个 Avatar 的眨眼・视线设置已错位。", "눈 깜빡임·시선 설정이 어긋난 아바타가 {0}개 있습니다. " } },
            { "Avatar Descriptor はシェイプを番号で参照しているため、並び替えでずれます。",
                new[] { "The Avatar Descriptor refers to shapes by index, so reordering shifts them.", "Avatar Descriptor 按编号引用形态键，因此重新排列会导致错位。", "Avatar Descriptor는 셰이프를 번호로 참조하므로 순서를 바꾸면 어긋납니다." } },
            { "反映（{0} 体）", new[] { "Apply ({0})", "应用（{0} 个）", "반영({0}개)" } },
            { "反映", new[] { "Apply", "应用", "반영" } },
            { "チェックした未反映のアバターに、反映するファイルを割り当てます",
                new[] { "Assign the file to apply to the checked avatars that are not applied yet", "将要应用的文件分配给勾选的未应用 Avatar", "체크한 미반영 아바타에 반영할 파일을 할당합니다" } },
            { "次のアバターは、作る前のファイルとは異なるファイルを使っています。反映すると顔のデータもこのファイルと同じになります。\n\n",
                new[] { "The following avatars use a file different from the original file. Applying will also make their face data the same as this file.\n\n",
                    "以下 Avatar 使用的文件与创建前的文件不同。应用后脸部数据也会变为与此文件相同。\n\n",
                    "다음 아바타는 만들기 전 파일과 다른 파일을 사용하고 있습니다. 반영하면 얼굴 데이터도 이 파일과 같아집니다.\n\n" } },
            { "・{0}（{1}）", new[] { "• {0} ({1})", "・{0}（{1}）", "• {0} ({1})" } },
            { "\n\n反映しますか？", new[] { "\n\nApply?", "\n\n要应用吗？", "\n\n반영하시겠습니까?" } },
            { "反映する", new[] { "Apply", "应用", "반영" } },
            { "反映前に戻す（{0} 体）", new[] { "Restore ({0})", "恢复到应用前（{0} 个）", "반영 전으로 되돌리기({0}개)" } },
            { "反映前に戻す", new[] { "Restore", "恢复到应用前", "반영 전으로 되돌리기" } },
            { "チェックした反映済みのアバターを、反映する前の状態（使っていたファイル・値・瞬き/視線）に戻します。保存したファイルは消えません",
                new[] { "Restore the checked applied avatars to their state before applying (file, values, blink/eye look). Saved files are not deleted",
                    "将勾选的已应用 Avatar 恢复到应用前的状态（使用的文件、值、眨眼/视线）。保存的文件不会被删除",
                    "체크한 반영된 아바타를 반영 전 상태(사용하던 파일·값·눈 깜빡임/시선)로 되돌립니다. 저장한 파일은 지워지지 않습니다" } },
            { "編集中のアバターも反映前に戻します。\n", new[] { "The avatar being edited will also be restored.\n", "正在编辑的 Avatar 也将恢复到应用前。\n", "편집 중인 아바타도 반영 전으로 되돌립니다.\n" } },
            { "戻したあとは、このウィンドウの「管理」タブは空になります（ファイルを割り当て直すと再び編集できます）。\n\n戻しますか？",
                new[] { "After restoring, the \"Manage\" tab of this window will be empty (you can edit again by reassigning the file).\n\nRestore?",
                    "恢复后，此窗口的“管理”标签将变为空（重新分配文件后可再次编辑）。\n\n要恢复吗？",
                    "되돌린 뒤에는 이 창의 \"관리\" 탭이 비게 됩니다(파일을 다시 할당하면 다시 편집할 수 있습니다).\n\n되돌리시겠습니까?" } },
            { "戻す", new[] { "Restore", "恢复", "되돌리기" } },
            { "瞬き・視線を付け直す（{0} 体）", new[] { "Fix Blink/Eye Look ({0})", "重新设置眨眼・视线（{0} 个）", "눈 깜빡임·시선 다시 설정({0}개)" } },
            { "瞬き・視線を付け直す", new[] { "Fix Blink/Eye Look", "重新设置眨眼・视线", "눈 깜빡임·시선 다시 설정" } },
            { "チェックしたアバターの Avatar Descriptor の瞬き・視線を、同じ名前のシェイプを指すように付け直します",
                new[] { "Reassign the Avatar Descriptor blink/eye look of the checked avatars to point at shapes with the same names",
                    "将勾选 Avatar 的 Avatar Descriptor 眨眼・视线重新设置为指向同名的形态键",
                    "체크한 아바타의 Avatar Descriptor 눈 깜빡임·시선을 같은 이름의 셰이프를 가리키도록 다시 설정합니다" } },
            { "チェックしたアバターのうち、操作できないものは対象外になります。",
                new[] { "Checked avatars that cannot be processed are skipped.", "勾选的 Avatar 中无法操作的将被排除。", "체크한 아바타 중 작업할 수 없는 것은 제외됩니다." } },
            { "（編集中）", new[] { " (Editing)", "（编辑中）", " (편집 중)" } },
            { "（非表示）", new[] { " (Hidden)", "（隐藏）", " (숨김)" } },
            { "クリックで Hierarchy で選択", new[] { "Click to select in the Hierarchy", "点击在 Hierarchy 中选择", "클릭하여 Hierarchy에서 선택" } },
            { "反映するファイルと同じ", new[] { "same as the file to apply", "与要应用的文件相同", "반영할 파일과 같음" } },
            { "元のファイルと同じ", new[] { "same as the original file", "与原文件相同", "원래 파일과 같음" } },
            { "元のファイルと異なる", new[] { "different from the original file", "与原文件不同", "원래 파일과 다름" } },
            { "戻すと：{0}", new[] { "Restores to: {0}", "恢复后：{0}", "되돌리면: {0}" } },
            { "「反映前に戻す」を押したときに戻る先です", new[] { "Where the avatar goes back to when you press \"Restore\"", "点击“恢复到应用前”时恢复的目标", "\"반영 전으로 되돌리기\"를 눌렀을 때 돌아가는 곳입니다" } },
            { "瞬き・視線：✓ 正しい", new[] { "Blink/eye look: ✓ OK", "眨眼・视线：✓ 正确", "눈 깜빡임·시선: ✓ 정상" } },
            { "Avatar Descriptor の瞬き・視線は今の並びに合っています",
                new[] { "The Avatar Descriptor blink/eye look match the current order", "Avatar Descriptor 的眨眼・视线与当前顺序一致", "Avatar Descriptor의 눈 깜빡임·시선이 현재 순서와 맞습니다" } },
            { "瞬き・視線：⚠ ずれています（並び替え前の設定のまま）",
                new[] { "Blink/eye look: ⚠ Shifted (still set for the old order)", "眨眼・视线：⚠ 已错位（仍为排列前的设置）", "눈 깜빡임·시선: ⚠ 어긋남(정렬 전 설정 그대로)" } },
            { "Avatar Descriptor はシェイプを番号で参照しているため、並び替えでずれています。チェックして「瞬き・視線を付け直す」を押してください",
                new[] { "The Avatar Descriptor refers to shapes by index, so reordering shifted them. Check the avatar and press \"Fix Blink/Eye Look\"",
                    "Avatar Descriptor 按编号引用形态键，因此因重新排列而错位。请勾选后点击“重新设置眨眼・视线”",
                    "Avatar Descriptor는 셰이프를 번호로 참조하므로 순서를 바꾸어 어긋났습니다. 체크한 뒤 \"눈 깜빡임·시선 다시 설정\"을 누르세요" } },
            { "瞬き・視線：？ 確認できません", new[] { "Blink/eye look: ? Cannot verify", "眨眼・视线：？ 无法确认", "눈 깜빡임·시선: ? 확인할 수 없음" } },
            { "並び替えたときにこのアバターを開いていなかったため、ずれているか判断できません。Avatar Descriptor の瞬き・視線を確認してください",
                new[] { "This avatar was not open when the order was changed, so it cannot be determined whether it shifted. Check the Avatar Descriptor blink/eye look",
                    "重新排列时未打开此 Avatar，因此无法判断是否错位。请检查 Avatar Descriptor 的眨眼・视线",
                    "순서를 바꿀 때 이 아바타를 열어 두지 않아 어긋났는지 판단할 수 없습니다. Avatar Descriptor의 눈 깜빡임·시선을 확인하세요" } },
            { "✓ 反映済み", new[] { "✓ Applied", "✓ 已应用", "✓ 반영됨" } },
            { "反映できません", new[] { "Cannot Apply", "无法应用", "반영할 수 없음" } },
            { "未反映", new[] { "Not Applied", "未应用", "미반영" } },
            { "同じオブジェクト（{0}）が見つかりません", new[] { "The same object ({0}) cannot be found", "找不到相同的对象（{0}）", "같은 오브젝트({0})를 찾을 수 없습니다" } },
            { "メッシュが設定されていません", new[] { "No mesh is assigned", "未设置网格", "메시가 설정되어 있지 않습니다" } },
            { "顔のデータの形（頂点数）が違うため反映できません", new[] { "Cannot apply because the face data shape (vertex count) is different", "脸部数据的形状（顶点数）不同，无法应用", "얼굴 데이터의 형태(정점 수)가 달라 반영할 수 없습니다" } },
            { "反映の履歴", new[] { "Apply History", "应用记录", "반영 기록" } },
            { "{0:MM/dd HH:mm}　{1} 体に反映（{2}）", new[] { "{0:MM/dd HH:mm}  Applied to {1} ({2})", "{0:MM/dd HH:mm}　应用到 {1} 个（{2}）", "{0:MM/dd HH:mm}  {1}개에 반영({2})" } },
            { "取り消し済み", new[] { "Undone", "已撤销", "취소됨" } },
            { "残り {0} 体を取り消す", new[] { "Undo Remaining {0}", "撤销剩余 {0} 个", "남은 {0}개 취소" } },
            { "この反映を取り消す", new[] { "Undo This Apply", "撤销此次应用", "이 반영 취소" } },
            { "この回に反映したアバターを、反映前の状態に戻します",
                new[] { "Restore the avatars applied this time to their state before applying", "将此次应用的 Avatar 恢复到应用前的状态", "이번에 반영한 아바타를 반영 전 상태로 되돌립니다" } },
            { "・{0}（シーンに見つかりません）", new[] { "• {0} (not found in the scene)", "・{0}（在场景中找不到）", "• {0} (씬에서 찾을 수 없음)" } },
            { "・{0}（すでに別のファイルを使っています）", new[] { "• {0} (already uses a different file)", "・{0}（已在使用其他文件）", "• {0} (이미 다른 파일을 사용 중)" } },
            { "取り消せるアバターがありません。\n\n", new[] { "There are no avatars that can be undone.\n\n", "没有可以撤销的 Avatar。\n\n", "취소할 수 있는 아바타가 없습니다.\n\n" } },
            { "{0:MM/dd HH:mm} の反映を取り消し、次のアバターを反映前の状態に戻します。\n\n",
                new[] { "Undo the apply from {0:MM/dd HH:mm} and restore the following avatars to their state before applying.\n\n",
                    "撤销 {0:MM/dd HH:mm} 的应用，并将以下 Avatar 恢复到应用前的状态。\n\n",
                    "{0:MM/dd HH:mm}의 반영을 취소하고, 다음 아바타를 반영 전 상태로 되돌립니다.\n\n" } },
            { "・{0}　→ {1}", new[] { "• {0}  → {1}", "・{0}　→ {1}", "• {0}  → {1}" } },
            { "\n\n次のアバターは対象外です：\n", new[] { "\n\nThe following avatars are skipped:\n", "\n\n以下 Avatar 不在范围内：\n", "\n\n다음 아바타는 대상에서 제외됩니다:\n" } },
            { "取り消す", new[] { "Undo", "撤销", "취소" } },
            { "{0}（反映前の記録なし・作る前の顔）", new[] { "{0} (no pre-apply record, original face)", "{0}（无应用前记录・创建前的脸）", "{0}(반영 전 기록 없음·만들기 전 얼굴)" } },
            { "（反映前のファイルが見つかりません。作る前の顔に戻します）",
                new[] { "(The pre-apply file cannot be found. Restores to the original face)", "（找不到应用前的文件。将恢复为创建前的脸）", "(반영 전 파일을 찾을 수 없습니다. 만들기 전 얼굴로 되돌립니다)" } },
            { "「{0}」の反映前のファイルが見つからないため、記録どおりには戻せませんでした。",
                new[] { "Could not restore \"{0}\" exactly as recorded because its pre-apply file cannot be found.", "找不到“{0}”应用前的文件，因此无法按记录恢复。", "\"{0}\"의 반영 전 파일을 찾을 수 없어 기록대로 되돌리지 못했습니다." } },
            { "反映前の状態に戻します（反映前の記録が無いアバターは、シェイプを作る前の顔に戻ります）。\n\n",
                new[] { "Restore to the state before applying (avatars with no pre-apply record go back to the face before shapes were created).\n\n",
                    "将恢复到应用前的状态（没有应用前记录的 Avatar 会恢复为创建形态键前的脸）。\n\n",
                    "반영 전 상태로 되돌립니다(반영 전 기록이 없는 아바타는 셰이프를 만들기 전 얼굴로 돌아갑니다).\n\n" } },
            { "このファイル（{0}）は、このアバターを含めて {1} 体のアバターが使っています。\n",
                new[] { "This file ({0}) is used by {1} avatars, including this one.\n", "此文件（{0}）包括此 Avatar 在内，共有 {1} 个 Avatar 在使用。\n", "이 파일({0})은 이 아바타를 포함해 {1}개의 아바타가 사용하고 있습니다.\n" } },
            { "どの範囲を戻しますか？", new[] { "Which avatars do you want to restore?", "要恢复哪些范围？", "어느 범위를 되돌리시겠습니까?" } },
            { "このアバターだけ戻す", new[] { "This Avatar Only", "仅恢复此 Avatar", "이 아바타만 되돌리기" } },
            { "全アバター（{0} 体）を戻す", new[] { "All Avatars ({0})", "恢复全部 Avatar（{0} 个）", "모든 아바타({0}개) 되돌리기" } },

            // ---------------------------------------------------------------- 保存ファイル
            { "このアバター用に作ったシェイプがあります。もう一度作る必要はありません。",
                new[] { "Shapes have already been created for this avatar. You do not need to create them again.", "已有为此 Avatar 创建的形态键，无需重新创建。", "이 아바타용으로 만든 셰이프가 있습니다. 다시 만들 필요는 없습니다." } },
            { "不要になったファイルは「削除」で整理できます（「管理 › 設定」からも整理できます）。",
                new[] { "Files you no longer need can be removed with \"Delete\" (also available in \"Manage › Settings\").", "不需要的文件可以通过“删除”整理（也可以在“管理 › 设置”中整理）。", "필요 없어진 파일은 \"삭제\"로 정리할 수 있습니다(\"관리 › 설정\"에서도 정리할 수 있습니다)." } },
            { "このアバターに使う", new[] { "Use for This Avatar", "用于此 Avatar", "이 아바타에 사용" } },
            { "保存済みのファイルをこのアバターに割り当てます", new[] { "Assign the saved file to this avatar", "将已保存的文件分配给此 Avatar", "저장된 파일을 이 아바타에 할당합니다" } },
            { "不要になったファイルを削除します（ごみ箱へ移動）", new[] { "Delete a file you no longer need (moves it to the trash)", "删除不需要的文件（移到回收站）", "필요 없어진 파일을 삭제합니다(휴지통으로 이동)" } },
            { "（使用中）", new[] { " (In Use)", "（使用中）", " (사용 중)" } },
            { "シェイプなし", new[] { "No shapes", "无形态键", "셰이프 없음" } },
            { "使っている場所を調べています…", new[] { "Looking for places that use it…", "正在查找使用位置…", "사용하는 곳을 찾고 있습니다…" } },
            { "「{0}」は次のアバターが使っているため削除できません。\n\n", new[] { "\"{0}\" cannot be deleted because it is used by the following avatars.\n\n", "“{0}”正被以下 Avatar 使用，无法删除。\n\n", "\"{0}\"은(는) 다음 아바타가 사용하고 있어 삭제할 수 없습니다.\n\n" } },
            { "\n\n先に「管理 › アバター管理」で「反映前に戻す」か、別のファイルを反映してください。",
                new[] { "\n\nFirst use \"Restore\" in \"Manage › Avatars\", or apply a different file.", "\n\n请先在“管理 › Avatar 管理”中“恢复到应用前”，或应用其他文件。", "\n\n먼저 \"관리 › 아바타 관리\"에서 \"반영 전으로 되돌리기\"를 하거나 다른 파일을 반영하세요." } },
            { "「{0}」を削除しますか？\n", new[] { "Delete \"{0}\"?\n", "要删除“{0}”吗？\n", "\"{0}\"을(를) 삭제하시겠습니까?\n" } },
            { "このファイルで作ったシェイプの設定も一緒に削除されます。ファイルはごみ箱に移動します。",
                new[] { "The settings of the shapes created in this file are deleted too. The file is moved to the trash.", "用此文件创建的形态键设置也会一并删除。文件将移到回收站。", "이 파일로 만든 셰이프 설정도 함께 삭제됩니다. 파일은 휴지통으로 이동합니다." } },
            { "\n\n⚠ 次のシーン・プレハブがこのファイルを使っています。削除するとそのメッシュが表示されなくなります。\n",
                new[] { "\n\n⚠ The following scenes/prefabs use this file. If you delete it, that mesh will no longer be displayed.\n",
                    "\n\n⚠ 以下场景・Prefab 正在使用此文件。删除后该网格将无法显示。\n",
                    "\n\n⚠ 다음 씬·프리팹이 이 파일을 사용하고 있습니다. 삭제하면 그 메시가 표시되지 않게 됩니다.\n" } },

            // ---------------------------------------------------------------- 設定タブ
            { "顔のデータの情報と、ふだんは変更しない設定です。", new[] { "Face data information and settings you normally do not need to change.", "脸部数据的信息，以及通常无需更改的设置。", "얼굴 데이터 정보와 평소에는 변경하지 않는 설정입니다." } },
            { "顔のデータ", new[] { "Face Data", "脸部数据", "얼굴 데이터" } },
            { "シェイプを作る前", new[] { "Before Shapes", "创建形态键前", "셰이프 만들기 전" } },
            { "シェイプは毎回このデータ（FBX など）から作り直します。このデータ自体は変更しません",
                new[] { "Shapes are rebuilt from this data (FBX, etc.) every time. This data itself is never modified", "每次都会从此数据（FBX 等）重新创建形态键。不会修改此数据本身", "셰이프는 매번 이 데이터(FBX 등)에서 다시 만듭니다. 이 데이터 자체는 변경하지 않습니다" } },
            { "保存したファイル", new[] { "Saved File", "保存的文件", "저장한 파일" } },
            { "作ったシェイプを追加した顔のデータです", new[] { "The face data with your created shapes added", "添加了已创建形态键的脸部数据", "만든 셰이프를 추가한 얼굴 데이터입니다" } },
            { "アバターを更新したとき", new[] { "When You Update the Avatar", "更新 Avatar 时", "아바타를 업데이트했을 때" } },
            { "アバターを新しいバージョンに更新したときや、顔のシェイプキーを修正したときに押してください。",
                new[] { "Press this after updating the avatar to a new version or modifying the face shape keys. ", "将 Avatar 更新到新版本，或修改了脸部形态键时请点击。", "아바타를 새 버전으로 업데이트했거나 얼굴 셰이프 키를 수정했을 때 누르세요. " } },
            { "作ったシェイプの設定はそのままで、最新の顔のデータに合わせて作り直します。",
                new[] { "Your shape settings are kept, and the shapes are rebuilt from the latest face data.", "保留已创建形态键的设置，并根据最新的脸部数据重新创建。", "만든 셰이프 설정은 그대로 두고 최신 얼굴 데이터에 맞춰 다시 만듭니다." } },
            { "最新のアバターに合わせて作り直す", new[] { "Rebuild for the Latest Avatar", "根据最新 Avatar 重新创建", "최신 아바타에 맞춰 다시 만들기" } },
            { "作ったシェイプは作成した時点の顔のデータを使っているため、アバターを更新しても自動では反映されません",
                new[] { "Created shapes use the face data from when they were created, so updating the avatar does not update them automatically",
                    "已创建的形态键使用的是创建时的脸部数据，因此更新 Avatar 后不会自动反映",
                    "만든 셰이프는 만든 시점의 얼굴 데이터를 사용하므로 아바타를 업데이트해도 자동으로 반영되지 않습니다" } },
            { "このアバター用に作ったファイル", new[] { "Files Created for This Avatar", "为此 Avatar 创建的文件", "이 아바타용으로 만든 파일" } },
            { "不要になったファイルは削除できます。使用中のファイルは削除できません。", new[] { "You can delete files you no longer need. Files in use cannot be deleted.", "可以删除不需要的文件。使用中的文件无法删除。", "필요 없어진 파일은 삭제할 수 있습니다. 사용 중인 파일은 삭제할 수 없습니다." } },
            { "退避用の見出し", new[] { "Backup Header", "备份用标题", "백업용 제목" } },
            { "既存のシェイプを上書きしたとき、退避した元のシェイプはこの見出しの下にまとめて置きます。",
                new[] { "When you overwrite an existing shape, the backed-up original shapes are grouped under this header. ", "覆盖现有形态键时，备份的原形态键会集中放在此标题下方。", "기존 셰이프를 덮어쓸 때 백업한 원래 셰이프는 이 제목 아래에 모아 둡니다. " } },
            { "既存の見出し（例: ---- VRCHAT ----）と同じ名前にすると、その下に置きます。",
                new[] { "If you use the same name as an existing header (e.g. ---- VRCHAT ----), they are placed under it.", "如果与现有标题（例：---- VRCHAT ----）同名，则放在其下方。", "기존 제목(예: ---- VRCHAT ----)과 같은 이름으로 하면 그 아래에 둡니다." } },
            { "見出しの名前", new[] { "Header Name", "标题名称", "제목 이름" } },
            { "退避名の接尾辞", new[] { "Backup Name Suffix", "备份名称后缀", "백업 이름 접미사" } },
            { "既存のシェイプを上書きしたとき、元のシェイプはこの接尾辞を付けた名前で残します。",
                new[] { "When you overwrite an existing shape, the original shape is kept with this suffix added to its name.", "覆盖现有形态键时，原形态键会以添加此后缀的名称保留。", "기존 셰이프를 덮어쓸 때 원래 셰이프는 이 접미사를 붙인 이름으로 남깁니다." } },
            { "接尾辞", new[] { "Suffix", "后缀", "접미사" } },
            { "シェイプを作成すると変更できるようになります。", new[] { "This can be changed after you create a shape.", "创建形态键后即可更改。", "셰이프를 만들면 변경할 수 있게 됩니다." } },

            // ---------------------------------------------------------------- 保存・Undo・ログ
            { "保存中にエラーが発生しました。詳細は Console を確認してください。\n\n", new[] { "An error occurred while saving. See the Console for details.\n\n", "保存时发生错误。详情请查看 Console。\n\n", "저장 중 오류가 발생했습니다. 자세한 내용은 Console을 확인하세요.\n\n" } },
            { "対象メッシュの状態が変わっています。対象メッシュを指定し直してから、もう一度お試しください。",
                new[] { "The target mesh has changed. Assign the target mesh again and try again.", "目标网格的状态已改变。请重新指定目标网格后再试一次。", "대상 메시의 상태가 바뀌었습니다. 대상 메시를 다시 지정한 뒤 다시 시도하세요." } },
            { "シェイプを作成しています…", new[] { "Creating shapes…", "正在创建形态键…", "셰이프를 만들고 있습니다…" } },
            { "シェイプの並びが変わったため、同じファイルを使う他のアバター {0} 体の瞬き・視線の設定がずれています。",
                new[] { "Because the shape order changed, blink/eye look settings on {0} other avatars using the same file are now shifted. ",
                    "由于形态键顺序已改变，使用同一文件的其他 {0} 个 Avatar 的眨眼・视线设置已错位。",
                    "셰이프 순서가 바뀌어 같은 파일을 쓰는 다른 아바타 {0}개의 눈 깜빡임·시선 설정이 어긋났습니다. " } },
            { "「管理 › アバター管理」で付け直してください。", new[] { "Fix them in \"Manage › Avatars\".", "请在“管理 › Avatar 管理”中重新设置。", "\"관리 › 아바타 관리\"에서 다시 설정하세요." } },
            { "メッシュを保存", new[] { "Save Mesh", "保存网格", "메시 저장" } },
            { "シェイプを追加したメッシュの保存先", new[] { "Where to save the mesh with the added shapes", "添加了形态键的网格的保存位置", "셰이프를 추가한 메시의 저장 위치" } },
            { "[{0}] 保存しました: {1}", new[] { "[{0}] Saved: {1}", "[{0}] 已保存：{1}", "[{0}] 저장했습니다: {1}" } },
            { "Avatar Descriptor の瞬き・視線で使っていた「{0}」が無くなったため、割り当てを解除しました。",
                new[] { "\"{0}\", used for the Avatar Descriptor blink/eye look, no longer exists, so it was unassigned.", "Avatar Descriptor 眨眼・视线所使用的“{0}”已不存在，因此已解除分配。", "Avatar Descriptor의 눈 깜빡임·시선에서 사용하던 \"{0}\"이(가) 없어져 할당을 해제했습니다." } },
            { "シェイプ名「{0}」が重複しています（後のものを使用）", new[] { "Shape name \"{0}\" is duplicated (the later one is used)", "形态键名称“{0}”重复（使用后者）", "셰이프 이름 \"{0}\"이(가) 중복됩니다(뒤의 것을 사용)" } },
            { "[{0}] {1} 体のアバターの瞬き・視線を付け直しました。", new[] { "[{0}] Fixed blink/eye look on {1} avatars.", "[{0}] 已重新设置 {1} 个 Avatar 的眨眼・视线。", "[{0}] 아바타 {1}개의 눈 깜빡임·시선을 다시 설정했습니다." } },
            { "[{0}] {1} 体のアバターに反映しました。", new[] { "[{0}] Applied to {1} avatars.", "[{0}] 已应用到 {1} 个 Avatar。", "[{0}] 아바타 {1}개에 반영했습니다." } },
            { "[{0}] {1} 体の反映を取り消しました。", new[] { "[{0}] Undid the apply on {1} avatars.", "[{0}] 已撤销 {1} 个 Avatar 的应用。", "[{0}] 아바타 {1}개의 반영을 취소했습니다." } },
            { "[{0}] {1} 体のアバターを反映前に戻しました。", new[] { "[{0}] Restored {1} avatars.", "[{0}] 已将 {1} 个 Avatar 恢复到应用前。", "[{0}] 아바타 {1}개를 반영 전으로 되돌렸습니다." } },
            { "[{0}] {1} をごみ箱に移動しました。", new[] { "[{0}] Moved {1} to the trash.", "[{0}] 已将 {1} 移到回收站。", "[{0}] {1}을(를) 휴지통으로 이동했습니다." } },
            { "[{0}] {1} を削除できませんでした。", new[] { "[{0}] Could not delete {1}.", "[{0}] 无法删除 {1}。", "[{0}] {1}을(를) 삭제하지 못했습니다." } },
            { " (瞬き・視線の付け直し)", new[] { " (Fix Blink/Eye Look)", "（重新设置眨眼・视线）", " (눈 깜빡임·시선 다시 설정)" } },
            { " (反映)", new[] { " (Apply)", "（应用）", " (반영)" } },
            { " (反映前に戻す)", new[] { " (Restore)", "（恢复到应用前）", " (반영 전으로 되돌리기)" } },
            { " (反映の取り消し)", new[] { " (Undo Apply)", "（撤销应用）", " (반영 취소)" } },
            { " (元に戻す)", new[] { " (Restore)", "（恢复）", " (되돌리기)" } },
            { "    (作成済み)", new[] { "    (created)", "    （已创建）", "    (만듦)" } },
            { "{0} 上で値が入っているシェイプはありません", new[] { "No shapes have a value on {0}", "{0} 上没有已设置值的形态键", "{0}에서 값이 들어 있는 셰이프가 없습니다" } },
            { "シェイプキー", new[] { "Shape Keys", "形态键", "셰이프 키" } },
        };
    }
}
